spring:
  datasource:
    url: ENC(m53x+SvRqrxM5f5NQwDbtDnzQjPpmClbbA403jPdXWHzB/3QWAW0fwa/r+ap90e6ahbXaafYUWtrn06mLdmH/wDFmK7zKZX9hpDzWAzJdC7B/wS0pXV0mXrh0KA2ErhuWH1VCDtwL0EuKXbExpu+ZA==)
    username: ENC(Larpmt96bwDG1E1OlMtpqw==)
    password: ENC(/xL42mojrSTxPmMtZZUu+y3KldseXmuN)
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      show-sql: true
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndTripleDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
