name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TK }}
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        working-directory: ./collabstack-be
        context: .
        builder: ${{ steps.buildx.outputs.name }}
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/collabstack-be:latest
