name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Grant execute permission for gradlew
      working-directory: ./collabstack-be
      run: chmod +x ./gradlew
    - name: Build with Gradle
      working-directory: ./collabstack-be
      run: ./gradlew build -x test
      
    - name: Build the Docker image
      working-directory: ./collabstack-be
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TK }}
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        working-directory: ./collabstack-be
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./collabstack-be
        file: ./collabstack-be/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/collabstack-be:latest
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Action
        uses: invi5H/ssh-action@v1.0.0
        with:
          # A unique name for the server
          SSH_USER: ubuntu
          # The hostname or the IP address
          SSH_HOST: ${{ secrets.BACKEND_EC2_HOST }}
          SSH_KEY: ${{ secrets.BACKEND_EC2_KEY }}
          script: sudo ./run.sh
