name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Grant execute permission for gradlew
      working-directory: ./collabstack-be
      run: chmod +x ./gradlew
    - name: Build with Gradle
      working-directory: ./collabstack-be
      run: ./gradlew build -x test
      
    - name: Build the Docker image
      working-directory: ./collabstack-be
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TK }}
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        working-directory: ./collabstack-be
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./collabstack-be
        file: ./collabstack-be/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/collabstack-be:latest
    - name: Deploy to ec2
      uses: kevin-leptons/ssh_action@v1
      with:
        # URI refers to remote host like `user@host`
        host: ${{ secrets.BACKEND_EC2_HOST }}
        # Private SSH key to authenticate
        key: ${{ secrets.BACKEND_EC2_KEY }}
        # Command to execute, Bash syntax
        command: sudo ./run.sh
